### ISSUE TITLE
configure file missing in git

### ISSUE THREAD

**Issue by pvautee** [theonewolf/libperf#3]
Hi,

Tried to download this user-space library and followed README instructions to install it.
But, I am not able to find configure file in downloaded source code.
Could you please help me to run this libperf?

**Comment by theonewolf** [comment]
Try running `bootstrap.sh` first.  The configure script needs to be auto-generated.

**Comment by pvautee** [comment]
Hi Wolf,
Thanks for your quick help.
I did ./bootstrap.sh and got configure file. I am getting below error:

``` bash
# ./configure
configure: error: cannot find sources (src/perf_event.h) in . or ..
```

I have this kernel with perf installed on it.
Thanks in advance.

**Comment by theonewolf** [comment]
@pvautee let me know if this is fixed, it got auto-closed by my commit.
